yourub_defaults: &yourub_defaults
  developer_key: 'AIzaSyDfP0U1mHMeycwlsm1kWCCSQrgUCDJU9J8'
  youtube_api_service_name: 'youtube'
  youtube_api_version: 'v3'
  application_name: "PITBULL"
  application_version: "0.1"
  log_level: WARN

development:
  <<: *yourub_defaults

production:
  <<: *yourub_defaults

test:
  <<: *yourub_defaults